org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.sdkPath=/root/Android/Sdk
android.buildToolsVersion=36.1.0
android.suppressUnsupportedCompileSdk=34
android.enableResourceStreaming=false
android.enableResourceOptimizations=false
android.aapt2FromMavenOverride=/root/Android/Sdk/build-tools/36.1.0/aapt2
