org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.sdkPath=/root/Android/Sdk
android.buildToolsVersion=33.0.1
android.suppressUnsupportedCompileSdk=34
android.enableResourceStreaming=false
android.aapt2FromMavenOverride=/workspace/MCP-Run/aapt2
android.enableResourceOptimizations=false
